version: "3.9"

services:

  db:
    image: postgres:15
    container_name: postgres-transport
    restart: always
    environment:
      POSTGRES_DB: transporte_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: transport-api
    depends_on:
      - db
    ports:
      - "8080:8080"
