spring:
  application:
    name: transport-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/transporte_db
    username: transporte_user
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # cria tabelas automaticamente
    show-sql: true       # mostra SQL no console
    properties:
      hibernate:
        format_sql: true
